### ISSUE TITLE
[BUG] Get Mesh doesn't import mesh from terminal

### ISSUE THREAD

**Issue by opedog** [The-EG/OctoPrint-UBLMeshEdit#10]
**Describe the bug**
I hit Get Mesh and nothing shows up

**M420 Output**
![image](https://user-images.githubusercontent.com/803567/110350628-ea59ac00-8001-11eb-9174-e46ea0b978e2.png)
![image](https://user-images.githubusercontent.com/803567/110350754-09583e00-8002-11eb-8ade-35081e3d722e.png)

**Firmware**
ender 3 pro, marlin v2 i compiled myself in the last 2 weeks from th3d unified

**Comment by opedog** [comment]
I'd be happy to provide any other information!

**Comment by The-EG** [comment]
Hey, someone actually read the notice!

Ok, this *looks* like it's Mesh Bed Leveling (MBL) not Unified Bed Leveling (UBL) or ABL. It looks like it's similar enough to ABL that I can probably get it to pick it up, but the same caveats will apply (only basic functionality).

If it *is* MBL, I'd recommend trying out UBL. You can still use it without a probe (you need to also enable `#define PROBE_MANUALLY`. The process is similar, but you get the extra features of UBL like storing multiple meshes and it behaves much better (MBL treats a mesh with all 0's as invalid, etc.)

**Comment by opedog** [comment]
OH CRAP I'm so sorry you're right this is MBL.  You can close this.  Mea culpa!
