### ISSUE TITLE
[BUG] New Issue

### ISSUE THREAD

**Issue by GK-3D** [The-EG/OctoPrint-UBLMeshEdit#11]
**Describe the bug**

**M420 Output**
If this bug is related to the mesh not loading or updating properly, include the output of `M420 V1 T1` including the last 'ok'.

**Firmware**
What firmware (vanilla Marlin, etc), what version and is it a precompiled binary? If precompiled, where is it from? (Vendor, marlin.crc.in.au, etc.)

**Comment by The-EG** [comment]
It looks like this was opened in error. If not, please provide the appropriate info and re-open.
